spring.application.name=ecommerce-api

# H2 database config (in memory)
spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# hibernate : generate and update sql's tables automatically with @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# activate H2 web console to view the database in browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console